service: emailScheduler

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "ses:SendEmail"
        - "ses:SendRawEmail"
        - "s3:*"
      Resource:
        - "arn:aws:dynamodb:ap-southeast-1:978606118148:table/*"
        - "*" 
        - "arn:aws:s3:::email-scheduler-attachments-test"
functions:
  emailScheduler:
    handler: src/handler.emailScheduler

plugins:
  - serverless-offline
