service: receiveMessageFromSQS

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "s3-object-lambda:*"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:PutItem"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:GetQueueAttributes"
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource:
        - "arn:aws:s3:::*"
        - "arn:aws:dynamodb:ap-southeast-1:978606118148:table/*"
        - "arn:aws:sqs:ap-southeast-1:978606118148:email-campaign"
        - "*"
functions:
  emailCampaign:
    handler: src/handler.lambda_handler

plugins:
  - serverless-offline
